import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
const fail=(message,status=400)=>Object.assign(Error(message),{status});
function key(){const raw=process.env.COP_CREDENTIALS_KEY;if(!/^[a-f0-9]{64}$/i.test(raw||''))throw fail('Chave de criptografia do COP não configurada.',503);return Buffer.from(raw,'hex');}
export function encryptSecret(value){if(typeof value!=='string'||!value||value.length>8192)throw fail('Credencial inválida.');const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);return ['v1',iv.toString('base64'),cipher.update(value,'utf8','base64')+cipher.final('base64'),cipher.getAuthTag().toString('base64')].join('.');}
export function decryptSecret(value){if(!value)return '';try{const [version,iv,data,tag]=value.split('.');if(version!=='v1')throw Error();const cipher=createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64'));cipher.setAuthTag(Buffer.from(tag,'base64'));return cipher.update(data,'base64','utf8')+cipher.final('utf8');}catch{throw fail('Não foi possível abrir a credencial cadastrada.',503);}}
export const tokenHash=value=>createHash('sha256').update(value).digest('hex');
const text=(value,label,max=120,required=true)=>{if(typeof value!=='string'||value.trim().length>max||required&&!value.trim())throw fail(label+' inválido.');return value.trim()||null;};
const port=(value,fallback)=>{const n=Number(value??fallback);if(!Number.isInteger(n)||n<1||n>65535)throw fail('Porta inválida.');return n;};
export function validateDirectory(value){const v=text(value,'Diretório',240);if(!/^[A-Za-z0-9_.-]+(?:\/[A-Za-z0-9_.-]+)*$/.test(v)||v.split('/').some(p=>p==='.'||p==='..'))throw fail('Use um diretório relativo, sem espaços ou .. (ex.: unidades/cerejeiras).');return v;}
export function validateServer(data){const name=text(data.name,'Servidor'),connector=text(data.connector_name,'Identificador',64);if(!/^[A-Za-z0-9_-]+$/.test(connector))throw fail('Identificador: use letras, números, _ ou -.');const host=text(data.host,'IP ou domínio',253);if(!/^[A-Za-z0-9.:[\]_-]+$/.test(host))throw fail('IP ou domínio inválido.');const root=text(data.storage_root,'Diretório base',240);if(!/^\/[A-Za-z0-9_.-]+(?:\/[A-Za-z0-9_.-]+)+$/.test(root)||root.split('/').some(p=>p==='..'||p==='.'))throw fail('Informe um diretório base absoluto.');if(typeof data.active!=='boolean')throw fail('Status inválido.');return {name,connector,host,root,ssh_port:port(data.ssh_port,22),registration_port:port(data.registration_port,8000),username:text(data.access_username||'','Usuário',120,false),active:data.active};}
export const publicServerSql="SELECT id,name,connector_name,host,ssh_port,registration_port,access_username,storage_root,active,created_at,updated_at,(token_cipher IS NOT NULL) token_saved,(access_password_cipher IS NOT NULL) password_saved,(private_key_cipher IS NOT NULL) private_key_saved FROM cop_servers ORDER BY name,id";
export const publicDvrSql="SELECT (to_jsonb(d)-'access_password_cipher') || jsonb_build_object('password_saved',d.access_password_cipher IS NOT NULL) AS item FROM cop_dvrs d ORDER BY unit_id,name";
export function redactDvr(row){const {access_password_cipher,...safe}=row;return {...safe,password_saved:!!access_password_cipher};}
export async function deviceAssignment(pool,data){const serverId=data.server_id||null,directoryId=data.server_directory_id||null;if(!serverId&&directoryId)throw fail('Selecione o servidor do diretório.');if(!serverId)return {serverId:null,directoryId:null,connector:data.sdk_connector_name||'hostinger'};const server=(await pool.query('SELECT * FROM cop_servers WHERE id=$1',[serverId])).rows[0];if(!server)throw fail('Servidor não encontrado.');if(directoryId){const dir=await pool.query('SELECT id FROM cop_server_directories WHERE id=$1 AND server_id=$2',[directoryId,serverId]);if(!dir.rowCount)throw fail('O diretório não pertence ao servidor selecionado.');}return {serverId,directoryId,connector:server.connector_name};}
export function createInfrastructureApi({pool,json,readJson}){return async(req,res,url)=>{
 const secret=url.pathname.match(/^\/api\/(servers|dvrs)\/([1-9]\d*)\/credentials$/);
 if(secret&&req.method==='GET'){const server=secret[1]==='servers';const row=(await pool.query(`SELECT * FROM ${server?'cop_servers':'cop_dvrs'} WHERE id=$1`,[secret[2]])).rows[0];if(!row)throw fail('Cadastro não encontrado.',404);return json(res,200,server?{token:decryptSecret(row.token_cipher),access_password:decryptSecret(row.access_password_cipher),private_key:decryptSecret(row.private_key_cipher)}:{access_password:decryptSecret(row.access_password_cipher)});}
 const match=url.pathname.match(/^\/api\/(servers|server-directories)(?:\/([1-9]\d*))?$/);if(!match)return false;
 const [,kind,id]=match;if(req.method==='GET'&&!id)return json(res,200,kind==='servers'?(await pool.query(publicServerSql)).rows:(await pool.query('SELECT * FROM cop_server_directories ORDER BY friendly_name,id')).rows);
 if(!['POST','PUT'].includes(req.method)||(req.method==='POST')===!!id)throw fail('Método não permitido.',405);
 const data=await readJson(req);if(data.clear_password&&data.access_password||data.clear_private_key&&data.private_key)throw fail('Para remover uma credencial, deixe seu campo vazio.');const client=await pool.connect();try{await client.query('BEGIN');let saved;
 if(kind==='servers'){const v=validateServer(data),old=id?(await client.query('SELECT * FROM cop_servers WHERE id=$1 FOR UPDATE',[id])).rows[0]:{};if(!old)throw fail('Servidor não encontrado.',404);const token=data.token===undefined||data.token===''?old.token_cipher?decryptSecret(old.token_cipher):randomBytes(36).toString('base64url'):data.token;if(typeof token!=='string'||token.length<32||token.length>512||/[\s\x00-\x1f]/.test(token))throw fail('Token: informe ao menos 32 caracteres, sem espaços.');const password=data.clear_password?null:data.access_password?encryptSecret(data.access_password):old.access_password_cipher||null;const privateKey=data.clear_private_key?null:data.private_key?encryptSecret(data.private_key):old.private_key_cipher||null;const values=[v.name,v.connector,v.host,v.ssh_port,v.registration_port,v.username,v.root,encryptSecret(token),tokenHash(token),password,privateKey,v.active];saved=id?await client.query(`UPDATE cop_servers SET name=$1,connector_name=$2,host=$3,ssh_port=$4,registration_port=$5,access_username=$6,storage_root=$7,token_cipher=$8,token_hash=$9,access_password_cipher=$10,private_key_cipher=$11,active=$12,updated_at=now() WHERE id=$13 RETURNING id`,[...values,id]):await client.query(`INSERT INTO cop_servers(name,connector_name,host,ssh_port,registration_port,access_username,storage_root,token_cipher,token_hash,access_password_cipher,private_key_cipher,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id`,values);
 if(id)await client.query('UPDATE cop_dvrs SET sdk_connector_name=$2,sdk_online=FALSE WHERE server_id=$1',[id,v.connector]);
 }else{const serverId=data.server_id;const server=await client.query('SELECT id FROM cop_servers WHERE id=$1',[serverId]);if(!server.rowCount)throw fail('Servidor não encontrado.');const values=[serverId,validateDirectory(data.directory_name),text(data.friendly_name,'Nome amigável')];if(id){const old=(await client.query('SELECT server_id FROM cop_server_directories WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!old)throw fail('Diretório não encontrado.',404);if(String(old.server_id)!==String(serverId))throw fail('Não é possível mover um diretório para outro servidor.');}saved=id?await client.query('UPDATE cop_server_directories SET directory_name=$1,friendly_name=$2 WHERE id=$3 RETURNING id',[values[1],values[2],id]):await client.query('INSERT INTO cop_server_directories(server_id,directory_name,friendly_name) VALUES($1,$2,$3) RETURNING id',values);}
 await client.query('COMMIT');return json(res,200,saved.rows[0]);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
 };}
